name: rideon
description: A passenger application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^1.0.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  intl: ^0.16.1
  provider: ^4.3.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+2
  flutter_secure_storage: ^3.3.5
  google_maps_flutter: ^1.2.0
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  google_api_headers: ">=0.1.0 <1.0.0"
  tuple: ^1.0.3
  http: ^0.12.0+4
  flutter_polyline_points: ^0.2.4
  firebase_messaging: ^7.0.3
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.0
 

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo.gif
  #   - images/a_dot_ham.jpeg

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
