name: rideon
description: A rides haring passenger application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  connectivity: ^3.0.6  
  dio: ^4.0.0
  flutter_secure_storage: ^4.2.0
  flutter_polyline_points: ^1.0.0  
  firebase_auth: ^1.2.0
  firebase_core : ^1.2.0
  firebase_messaging: ^10.0.0
  geolocator: ^7.0.3
  google_api_headers: ^1.0.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  intl: ^0.17.0
  location: ^4.1.1
  permission_handler: ^8.0.0+2
  provider: ^5.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
